- README.md
- lib/graphql-docs/client.rb
- test/graphql-docs/client_test.rb
Hello. Thank you for the useful gem!
Occasionally, I have to pass some custom headers such as `X-Api-Token: ....` or `Authorization: Bearer ....` to GraphQL servers. So I'd like to add the `:headers` option.
> Allow :headers option to send custom headers

- Rakefile
- lib/graphql-docs/generator.rb
This is misinterpreted by the Commonmark renderer as `pre` tags
Closes https://github.com/gjtorikian/graphql-docs/issues/23.
> Remove leading spaces when rendering content

- lib/graphql-docs/layouts/graphql_input_objects.html
The input fields for Input Objects are not currently rendering:
With the fix:
> Fix bug with Input Object fields

- README.md
- lib/graphql-docs/configuration.rb
- lib/graphql-docs/layouts/graphql_enums.html
- lib/graphql-docs/layouts/graphql_input_objects.html
- lib/graphql-docs/layouts/graphql_interfaces.html
- lib/graphql-docs/layouts/graphql_mutations.html
- lib/graphql-docs/layouts/graphql_objects.html
- lib/graphql-docs/layouts/graphql_unions.html
- lib/graphql-docs/layouts/includes/connections.html
- lib/graphql-docs/layouts/includes/fields.html
- lib/graphql-docs/layouts/includes/input_fields.html
- lib/graphql-docs/layouts/includes/notices.html
- lib/graphql-docs/layouts/includes/values.html
- lib/graphql-docs/parser.rb
At GitHub we have a few concepts that we'd like to include in our GraphQL documentation. For example, we mark some schema members as deprecated that normally cannot be deprecated as per the spec. We also have the concept of _schema previews_ which allow us to release parts of our schema behind a toggle.
Rather than hardcode these concepts into this documentation generator or having to copy over all the `layouts/` files into our repo, I've added a generic feature to `graphql-docs` that I called: notices.
A notice is a block of markdown text that optionally has a title which is displayed above a schema member's description. The look of a notice block can be controlled by specifying a custom class for it and then styled via CSS.
When the parser converts the schema into an internal …
> Add support for "notices" to schema members.

- lib/graphql-docs/layouts/includes/connections.html
- lib/graphql-docs/layouts/includes/input_fields.html
There are a few minor inconsistencies with how we're rendering type links / descriptions for connections and input fields.  These inconsistencies result in styles not being applied properly.
Connections / Input Fields:
* In fields.html, we wrap the link in a `<code>` tag, whereas it's the other way around for connections and input fields.  This isn't apparent in the sample docs page @ https://www.gjtorikian.com/graphql-docs/, but the styles in my project are affected by it.
Input Fields:
* In fields.html, we `markdownify` the field description which results in a `<p>` tag surrounding basic text.  For input fields, we use the raw description which causes the text to be squished vertically.  You can see it if you compare https://www.gjtorikian.com/graphql-docs/object/addcommentpayload/ with …
> Fix inconsistent styling of type links / input field descriptions

- lib/graphql-docs/generator.rb
- lib/graphql-docs/helpers.rb
As I understand it, In `GraphQLDocs::Generator` we perform whitespace normalization in order to prevent Markdown from interpreting whitespace at the beginning of an ERB ruby code tag.  For example, this prevents ERB like this:
```erb
<td>
<p><%= markdownify.(argument[:description]) %></p>
<% unless (default_value = argument[:default_value]).nil? %>
<p>The default value is <code><%= argument[:default_value] %></code>.</p>
<% end %>
</td>
```
...from having lines that just have 4 spaces on it (caused by the ERB tags that don't actually output content).  In Markdown, it'll then interpret those spaces and cause problems in the HTML.  The problem with this approach is that it also strips whitespace that is actually important in Markdown.
For example, if I add a code snippet in …
> Fix whitespace normalization causing indentation in code blocks to be incorrect

- lib/graphql-docs/layouts/includes/arguments.html
`markdownify` will already wrap argument descriptions in paragraph tags.  However, we've also explicitly wrapped paragraph tags around the `markdownify` content.  This results in two paragraph tags getting rendered.
For an example of this, see: https://www.gjtorikian.com/graphql-docs/object/query/
You'll notice that the description for the "search" connection is rendered with the following html:
```html
<td>
<p></p>
<p>Returns the first <em>n</em> elements from the list.</p>
</td>
```
Even though we see 2 separate tags in the html, they're actually nested when we render them in the code (i.e. it looks like `<p><p>Returns the first <em>n</em> elements from the list.</p></p>`).
This just removes the outer paragraph tags instead relying on `markdownify` to do the proper thing.  This more …
> Fix argument descriptions containing doubly nested paragraph tags

- lib/graphql-docs/generator.rb
- lib/graphql-docs/helpers.rb
- test/graphql-docs/generator_test.rb
This is a follow-up to https://github.com/gjtorikian/graphql-docs/pull/41.  Since the `<%` ERB tags are often indented, they don't get matched by ERB's `<>` trim mode option.  In http://docs.rubydocs.org/ruby-2-4-1/classes/ERB.html#method-c-new, the docs declare that the line must *start* with `<%`.
With this fix, we are matching lines that *end* with `%>`.  This will allow ERB to trim those lines properly.
Definitely double check me on this since I appear to have missed this in the last PR :)
@gjtorikian
> Fix ERB trim mode to match on %> instead of <%

- lib/graphql-docs/generator.rb
- lib/graphql-docs/helpers.rb
- test/graphql-docs/generator_test.rb
:disappointed: Third time's a charm?
Looks like I keep swinging and missing on this solution.  Turns out there were more use cases for the trimming than I was aware.  While the prior PR fixed scenarios where we have whitespace at the beginning of a line like so:
```
<% items.each do |item| %>
```
...it doesn't account for whitespace at the beginning of a line that outputs actual content.  For example:
```
<%= "test" %>
```
In the above scenario, Markdown would still interpret the 4 spaces at the beginning of the line and improperly modify the structure of the html.
As far as I can tell, we have 2 options.  Either (a) we have a separate renderer for markdown content vs. html content or (b) we only trim html content.
I've put together an implementation for solution (b).  Would love to hear …
> Only trim whitespace for html content

- .gitignore
- README.md
- Rakefile
- graphql-docs.gemspec
- lib/graphql-docs.rb
- lib/graphql-docs/parser.rb
- test/graphql-docs/graphql-docs_test.rb
- test/graphql-docs/parser_test.rb
From https://github.com/gjtorikian/graphql-docs/issues/47#issuecomment-387202189, this PR now allows for a `GraphQL::Schema` to be directly passed in.
cc @tobespangler-bic
Should close #47.
> Accept a schema

- lib/graphql-docs.rb
- lib/graphql-docs/generator.rb
- lib/graphql-docs/helpers.rb
- lib/graphql-docs/parser.rb
- test/graphql-docs/fixtures/named-root-schema.graphql
- test/graphql-docs/generator_test.rb
- test/graphql-docs/graphql-docs_test.rb
Fixes #52.
If the root type names are not the defaults (`Query`, `Mutation`, and the as-yet-unsupported-here `Subscription`) then they don't get correctly pulled into the top-level pages.
@gjtorikian note that I'm not rightly sure why mutations sometimes don't come up either, but I see that they seem to have quite different logic in the code which I don't understand. It's just that, given you're working on a PR in a similar area, I've pushed this earlier than I otherwise might!
Also, I'm not a Ruby guy. This probably needs a thorough look-over!
> Determine correct named root types

- Gemfile
- Rakefile
- graphql-docs.gemspec
- lib/graphql-docs.rb
- lib/graphql-docs/configuration.rb
- lib/graphql-docs/generator.rb
- lib/graphql-docs/helpers.rb
- lib/graphql-docs/parser.rb
- lib/graphql-docs/renderer.rb
- lib/graphql-docs/version.rb
- test/graphql-docs/generator_test.rb
- test/graphql-docs/graphql-docs_test.rb
- test/graphql-docs/parser_test.rb
- test/graphql-docs/renderer_test.rb
- test/test_helper.rb
I think I can achieve #51 (relative hrefs) through a mixture of a custom html-pipeline filter and some code in some custom layouts. However, in order to do so I need to know the filename that the file is being written to. This allows me to determine the 'depth' relative to some base path of the current file, and therefore add the right number of `../` entries to get out of there.
This pull request passes the filename through to the pipeline's context (on a per-file basis rather than the overarching pipeline-wide context).
Fixes #51.
> Pass filename through to HTML pipeline

- lib/graphql-docs/layouts/includes/connections.html
Problem
------------
Connection field descriptions are not parsed for markdown and deprecation notices aren't rendered for this particular field type.
Solution
------------
I used similar HTML as found in `graphql-docs/lib/graphql-docs/layouts/includes/fields.html` for rendering deprecation notices and wrapped `connection[:description]` in `markdownify.()`
> Add deprecations to connection fields

- README.md
The lambda syntax for the `options[:notices]` example was incorrect, and was setting `:notice` rather than `:notices`, which didn't work.
> Fix incorrect ruby syntax and :notice singular

- lib/graphql-docs/layouts/default.html
On mobile widths < 560px, the sidebar is not visible and the menu button did not trigger a change. This `onclick` listener will toggle the existing `sidebar-open` class to reveal or hide the sidebar for mobile users.
> Add event listener to toggle mobile sidebar

- graphql-docs.gemspec
- lib/graphql-docs/parser.rb
- test/graphql-docs/parser_test.rb
Upgrade graphql to address: 
* https://github.com/rmosolgo/graphql-ruby/pull/3765
* https://github.com/rmosolgo/graphql-ruby/pull/3750 
* 
Fixes :  #88
> Fix deprecation on graphql_definition ( Upgrade Graphql to 1.12.x)

- .github/workflows/tests.yml
- CHANGELOG.md
- README.md
- graphql-docs.gemspec
To get the latest ver of commonmarker, which has security vuln fixes,
this project needs to drop support for older Ruby versions. As of this
commit, the stable release series of Ruby are:
- 3.1
- 3.0
- 2.7
Ruby 2.6 is EOL but it seems to be working still, so this continues to
maintain support for it.
Addresses these dependabot alerts:
- https://github.com/brettchalupa/graphql-docs/security/dependabot/1
- https://github.com/brettchalupa/graphql-docs/security/dependabot/2
> Pin commonmarker to newer ver w/ security fixes & drop Ruby 2.5 support

- graphql-docs.gemspec
```
EscapeUtils.escape_html is deprecated. Use GCI.escapeHTML instead, it's faster
```
v2.14.3 has a fix to address that warning, so we want that as the
minimum version so people don't see that when generating their docs. See
https://github.com/gjtorikian/html-pipeline/pull/365 for reference.
Remove stricter pinning of `escape_utils` since we can use newer
version.
> chore: require latest ver of html-pipeline to address dep warning

- graphql-docs.gemspec
So the gemspec isn't satisfied by still vuln vers, see https://github.com/brettchalupa/graphql-docs/security/dependabot/1
> chore: be stricter about min commonmarker ver

- graphql-docs.gemspec
- lib/graphql-docs/generator.rb
The Ruby sass gem has been deprecated and is no longer actively maintained.
This replaces it with the dartsass gem, which uses a compiled ver of the
canonical sass compiler. It allows for `bundle exec dartsass` compile
styles. It has slightly different CLI options.
I'm truthfully on the fence about whether or not this project even needs
Sass, but it's easier to drop this in and maintain the existing
styles than to combine them all and deal with a 1k+ line stylesheet.
Fixes https://github.com/brettchalupa/graphql-docs/issues/86
BREAKING CHANGE: removes sass gem; if you rely on it, bundle it directly or call out to dartsass
---
This will be part of the upcoming 4.0.0 release.
> feat: replace Ruby sass with dartsass

- README.md
- exe/graphql-docs
- graphql-docs.gemspec
- test/cli_test.rb
- test/test_helper.rb
This allows those with the gem installed to use the `graphql-docs`
command, which (for now) has a simplified interface for generating the
site without needing to write any Ruby code.
A few notes:
- I'm certainly open to supporting as many options as possible, but
those would be great contributions from others who want to see them
- Uses `OptionParser` because I like it and it's in the standard library
- Has some naive option key transforming, which works for now but may
not be good enough for the long term
Finishes https://github.com/brettchalupa/graphql-docs/issues/2
Here's what running `graphql-docs --help` outputs:
``` console
Generate GraphQL docs from the passed in schema file.
Usage: graphql-docs SCHEMA
The only required argument is the path to the schema file to generate the site …
```
> Introduce CLI

- lib/graphql-docs/parser.rb
- test/graphql-docs/parser_test.rb
- test/test_helper.rb
Just like fields have deprecation information, add deprecation information for field arguments as well.
This is useful information that has been missing so far from the parser. It can be used by custom templates that display deprecated arguments differently, such as showing a warning or hiding the deprecated argument altogether.
The implementation follows the same logic as `field` a few lines above.
> feat(parser): add deprecation information for field arguments

- .github/workflows/tests.yml
- README.md
Ruby 2.6 is EOL and upstream dependencies require a more modern Ruby. I don't want to pin activesupport to be < 7 or something like that, so I think this works for now by not explicitly testing it on CI but calling out that the gem should work without issue.
This also adds Ruby 3.2 to the testing matrix.
Fixes https://github.com/brettchalupa/graphql-docs/issues/137
> Drop Ruby 2.6 on CI & add Ruby 3.2

- exe/graphql-docs
Add `graphql-docs -v` and `graphql-docs --version` to output the gem version.
This feature helps user know which version they're running. 
Fixes #145
> feat: Add version command with CLI

- CHANGELOG.md
- lib/graphql-docs/generator.rb
- test/cli_test.rb
- test/graphql-docs/parser_test.rb
summary of changes:
- fix(tests): new directive type in GH schema
- chore: add version flag to CHANGELOG & integration test
- fix(cli): remove `bundle exec` from dartsass run
- chore: update CHANGELOG
fixes https://github.com/brettchalupa/graphql-docs/issues/144
fixes https://github.com/brettchalupa/graphql-docs/issues/143
> Fix test suite & allow CLI to work outside of Bundler projects

- lib/graphql-docs/generator.rb
- lib/graphql-docs/helpers.rb
- lib/graphql-docs/renderer.rb
- test/graphql-docs/generator_test.rb
there were some breaking changes, I suspect in graphql-ruby commit https://github.com/rmosolgo/graphql-ruby/commit/15e70b80eba94a84172bb167d3b966d3313ca79b broke this after bisecting locally. the parser & lexer really massively changed. I truthfully don't understand it, and I believe they're pretty minor changes with how comments are parsed. So I think proceeding with skipping them and considering it a breaking change might be fine and then assess the impact.
fixes https://github.com/brettchalupa/graphql-docs/issues/149
> skip failing tests with graphql-ruby 2.2.0+

- graphql-docs.gemspec
- lib/graphql-docs/generator.rb
The dartsass gem has never been updated since its very first release. This PR updates to latest version of dart sass using sass-embedded gem, which has version and feature matching release with dart-sass.
> Update to latest sass with sass-embedded gem

- .github/workflows/tests.yml
- graphql-docs.gemspec
BREAKING CHANGE: those ruby versions are no longer maintained
This will be included in the v5.0.0 release
Fixes https://github.com/brettchalupa/graphql-docs/issues/139
> Drop EOL rubies 2.6, 2.7, 3.0

- CHANGELOG.md
- README.md
- lib/graphql-docs/version.rb
Release details:
- **breaking**: The graphql gem 2.2.0+ breaks some of the parsing and displaying of comments from a GraphQL schema file
- **breaking**: Ruby 2.6, 2.7, 3.0 are no longer supported as they are End of Life (EOL)
- feat: CLI version flag: `graphql-docs --version` / `graphql-docs -v`
- fix: CLI now works outside of a Bundler project
- fix: test suite
- chore: switch to sess-embedded gem for more maintained dependency
> Prepared for v5.0.0 release

- .rubocop.yml
Added 2 space idents to .rubocop.yml to be consistent with the code files having 2 spaces indents.
> 2 Space Indents

- graphql-docs.gemspec
- test/cli_test.rb
they're no longer going to be in the ruby std lib in future versions so
this adds them explicitly
this should get CI green again
> add logger and ostruct to gemspec

- .github/workflows/tests.yml
- graphql-docs.gemspec
- lib/graphql-docs/layouts/assets/css/screen.scss
- test/cli_test.rb
- **Output CLI errors in test assertions**
- **Pin minitest to latest minor ver** - fixes https://github.com/brettchalupa/graphql-docs/issues/157
- **Fix Sass `@import` deprecation** - fixes https://github.com/brettchalupa/graphql-docs/issues/158
> Address deprecation warnings with mutex_m and Sass @import

- .github/workflows/tests.yml
> Update Ruby 3.4 build to not use preview

- .github/workflows/tests.yml
I refined the on field by splitting the event triggers (push, pull_request) into separate lines, improving readability and making it easier to extend in the future. I simplified the step name from "Run the test suite" to "Run test suite" for conciseness and consistency in naming conventions. These changes help make the workflow file more readable, maintainable, and scalable, while also reducing redundancy. The overall functionality remains unchanged, but the structure is clearer for future adjustments or additions.
> Optimize GitHub Actions workflow: Simplified YAML structure and cleaned up step names.
